[workspace]
members = [
    "storeit_core",
    "storeit_macros",
    "storeit",
    "storeit_sql_builder",
    "storeit_mysql_async",
    "storeit_tokio_postgres",
    "storeit_libsql",
    "tests_common",
]
resolver = "2"


