[book]
title = "storeit-rs"
author = ["storeit-rs maintainers"]
language = "en"
multilingual = false
src = "src"

description = "Repository pattern for Rust with multiple SQL backends"

[build]
dist-dir = "book"
create-missing = true

[output.html]
default-theme = "light"
site-url = "/"
no-section-label = true
