name: Benches (non-blocking)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # daily at 04:00 UTC

jobs:
  bench-libsql:
    name: Criterion (storeit_libsql)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run benches (libsql only)
        run: cargo bench -p storeit_libsql --features libsql-backend --bench ops -- --quiet

      - name: Upload Criterion results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: criterion-libsql
          path: target/criterion/**
