name: Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  coverage:
    name: Generate coverage report
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) with llvm-tools
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Run coverage (HTML)
        run: |
          cargo llvm-cov --workspace --all-features --html --output-dir target/coverage/html

      - name: Run coverage (LCOV)
        run: |
          cargo llvm-cov --workspace --all-features --lcov --output-path target/coverage/lcov.info

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: target/coverage/html

      - name: Upload LCOV artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: target/coverage/lcov.info

      # Optional: upload to Codecov (uncomment and set CODECOV_TOKEN in repo secrets if needed for private repos)
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     files: target/coverage/lcov.info
      #     fail_ci_if_error: true
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
