name: Integration backends (Docker + coverage summary)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-and-coverage:
    name: ubuntu-latest (Docker)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install coverage tools
        run: |
          rustup component add llvm-tools-preview
          if ! command -v cargo-llvm-cov >/dev/null 2>&1; then
            cargo install cargo-llvm-cov --locked
          else
            echo "cargo-llvm-cov already installed"
          fi

      - name: Verify build (workspace)
        run: |
          cargo build --workspace --all-features

      - name: Run integration tests (containers) and coverage summary
        env:
          RUN_CONTAINERS: "1"
        run: |
          make coverage-all-summary

      - name: Upload coverage summary artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: |
            target/llvm-cov/
            lcov.info
          if-no-files-found: ignore
