name: Integration Backends (containers)

on:
  workflow_dispatch:
  schedule:
    - cron: '15 3 * * *'  # daily at 03:15 UTC

jobs:
  run-integration-tests:
    name: integration (${{ matrix.backend }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - backend: libsql
            package: storeit_libsql
            features: libsql-backend
          - backend: postgres
            package: storeit_tokio_postgres
            features: postgres-backend
          - backend: mysql
            package: storeit_mysql_async
            features: mysql-async
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Docker info
        run: docker version || true

      - name: Run ignored integration tests with containers
        env:
          # Ensure tests try to use containers (they also skip gracefully if Docker is unavailable)
          SKIP_CONTAINER_TESTS: "0"
        run: >-
          cargo test
          --package ${{ matrix.package }}
          --no-default-features
          --features ${{ matrix.features }}
          -- --ignored --nocapture
