use storeit_macros::Entity;
use storeit_core::Fetchable;

#[derive(Entity, Clone, Debug, PartialEq)]
struct User {
    #[fetch(id)]
    id: i64,
    email: String,
}

fn main() {
    // Ensure metadata constants are generated and have expected defaults.
    assert_eq!(User::TABLE, "users");
    assert_eq!(User::SELECT_COLUMNS, &["id", "email"]);
    // Ensure RowAdapter type is generated by the macro (name is <StructName>RowAdapter)
    let _adapter = UserRowAdapter;
    let _ = _adapter; // silence unused warning
}